from py.algos.swa import swa

print(str(swa('ACCTGCACATTGTGCACATGTACCCAAAAAAAAAGCGCGCGCGCGTTTTTTTACAGTATGAAAAAAAAAAAAACCCCACTCCTGG',
              'ACCTGCACATTGTGCACATGTACCCACAGTATCCTGCACATTGGCTTTTTTTACAGTATGACAGTATGACAGTCCCCACTCCTGG'))
      .replace(')', '').replace('(', '').replace(', ', '\n').replace('\'', ''))
